import freedomFriday from '../assets/ads/freedom_friday.png';
import freedomTv from '../assets/ads/freedom_tv.png';
import mobileFreedom from '../assets/ads/mobile_freedom_tv.png';
import freedomAd from '../assets/ads/ad1.png';
import { goToExtension } from '../utils/extension-utils';

export const adsConstant = [
  {
    url: '',
    path: freedomFriday,
    name: 'Freedom Friday coming soon',
    is_iframe: 'false',
    iframe: '',
    platform: 'arcade',
    priority: '3',
  },
  {
    url: '',
    path: '',
    name: 'home garden',
    is_iframe: 'true',
    iframe:
      '//rcm-na.amazon-adsystem.com/e/cm?o=1&p=12&l=ur1&category=homegarden&banner=0KHZXYBWZ0DYNJ4VZZ02&f=ifr&linkID=d48427d4dbc75799497142843a40ea7e&t=abstudios0d-20&tracking_id=abstudios0d-20',
    platform: 'coupons',
    priority: '1',
  },
  {
    url: '',
    path: '',
    name: 'standalone ad',
    is_iframe: 'true',
    iframe:
      '//rcm-na.amazon-adsystem.com/e/cm?o=1&p=48&l=ur1&category=beauty&banner=0Q2M96KTPZ1JX0G12SR2&f=ifr&linkID=143f9f796cfcf0365c2bdad6c679e563&t=abstudios0d-20&tracking_id=abstudios0d-20',
    platform: 'arcade',
    priority: '2',
  },
  {
    url: 'https://click.linksynergy.com/fs-bin/click?id=8o62EdvRBtw&offerid=873617.838&subid=0&type=4',
    path: 'https://ad.linksynergy.com/fs-bin/show?id=8o62EdvRBtw&bids=873617.838&subid=0&type=4&gridnum=16',
    name: 'bareMinerals',
    is_iframe: 'false',
    iframe: '',
    platform: 'arcade',
    priority: '6',
  },
  {
    url: 'https://click.linksynergy.com/fs-bin/click?id=8o62EdvRBtw&offerid=758409.4&subid=0&type=4',
    path: 'https://ad.linksynergy.com/fs-bin/show?id=8o62EdvRBtw&bids=758409.4&subid=0&type=4&gridnum=16',
    name: 'Jetson',
    is_iframe: 'false',
    iframe: '',
    platform: 'arcade',
    priority: '7',
  },
  {
    url: 'https://click.linksynergy.com/fs-bin/click?id=8o62EdvRBtw&offerid=731339.404&subid=0&type=4',
    path: 'https://ad.linksynergy.com/fs-bin/show?id=8o62EdvRBtw&bids=731339.404&subid=0&type=4&gridnum=10',
    name: 'NIC+ZOE (NICANDZOE, NIC&ZOE)',
    is_iframe: 'false',
    iframe: '',
    platform: 'rotate',
    priority: '1',
  },
  {
    url: 'https://channelstore.roku.com/en-ot/details/25d1bb353a476399904f57a98b99ab6e/freedom-tv-plus',
    path: freedomTv,
    name: 'Freedom Tv+ now on roku',
    is_iframe: 'false',
    iframe: '',
    platform: 'arcade',
    priority: '4',
  },
  {
    url: 'https://click.linksynergy.com/fs-bin/click?id=8o62EdvRBtw&offerid=791575.39&subid=0&type=4',
    path: 'https://ad.linksynergy.com/fs-bin/show?id=8o62EdvRBtw&bids=791575.39&subid=0&type=4&gridnum=10',
    name: 'Huda Beauty',
    is_iframe: 'false',
    iframe: '',
    platform: 'rotate',
    priority: '7',
  },
  {
    url: 'https://click.linksynergy.com/fs-bin/click?id=8o62EdvRBtw&offerid=717944.12&subid=0&type=4',
    path: 'https://ad.linksynergy.com/fs-bin/show?id=8o62EdvRBtw&bids=717944.12&subid=0&type=4&gridnum=9',
    name: 'Deal Parade Products',
    is_iframe: 'false',
    iframe: '',
    platform: 'rotate',
    priority: '5',
  },
  {
    url: 'https://click.linksynergy.com/fs-bin/click?id=8o62EdvRBtw&offerid=717944.3&subid=0&type=4',
    path: 'https://ad.linksynergy.com/fs-bin/show?id=8o62EdvRBtw&bids=717944.3&subid=0&type=4&gridnum=9',
    name: 'Deal Parade',
    is_iframe: 'false',
    iframe: '',
    platform: 'rotate',
    priority: '6',
  },
  {
    url: 'https://click.linksynergy.com/fs-bin/click?id=8o62EdvRBtw&offerid=923202.39&subid=0&type=4',
    path: 'https://ad.linksynergy.com/fs-bin/show?id=8o62EdvRBtw&bids=923202.39&subid=0&type=4&gridnum=9',
    name: 'Amora Coffee',
    is_iframe: 'false',
    iframe: '',
    platform: 'rotate',
    priority: '2',
  },
  {
    url: 'https://channelstore.roku.com/en-ot/details/25d1bb353a476399904f57a98b99ab6e/freedom-tv-plus',
    path: mobileFreedom,
    name: 'mobile Freedom Tv+ now on roku',
    is_iframe: 'false',
    iframe: '',
    platform: 'arcade',
    priority: '5',
  },
  {
    url: 'https://click.linksynergy.com/fs-bin/click?id=8o62EdvRBtw&offerid=843169.2359&subid=0&type=4',
    path: 'https://ad.linksynergy.com/fs-bin/show?id=8o62EdvRBtw&bids=843169.2359&subid=0&type=4&gridnum=9',
    name: 'The Luxury Closet',
    is_iframe: 'false',
    iframe: '',
    platform: 'rotate',
    priority: '8',
  },
  {
    url: 'https://click.linksynergy.com/fs-bin/click?id=8o62EdvRBtw&offerid=873617.20&subid=0&type=4',
    path: 'https://ad.linksynergy.com/fs-bin/show?id=8o62EdvRBtw&bids=873617.20&subid=0&type=4&gridnum=5',
    name: 'Free Shipping on Orders over $50',
    is_iframe: 'false',
    iframe: '',
    platform: 'extension',
    priority: '1',
  },
  {
    url: '',
    path: '',
    name: 'header box ad',
    is_iframe: 'true',
    iframe:
      '//rcm-na.amazon-adsystem.com/e/cm?o=1&p=12&l=ur1&category=homegarden&banner=0KHZXYBWZ0DYNJ4VZZ02&f=ifr&linkID=ac02042c89695323175666b751e6f50b&t=abstudios0d-20&tracking_id=abstudios0d-20',
    platform: 'arcade',
    priority: '1',
  },
  {
    url: 'https://click.linksynergy.com/fs-bin/click?id=8o62EdvRBtw&offerid=933876.6&subid=0&type=4&LSNSUBSITE=LSNSUBSITE',
    path: 'https://ad.linksynergy.com/fs-bin/show?id=8o62EdvRBtw&bids=933876.6&subid=0&type=4&gridnum=9',
    name: 'Men\'s Warehouse ',
    is_iframe: 'false',
    iframe: '',
    platform: 'rotate',
    priority: '4',
  },
  {
    url: 'https://click.linksynergy.com/fs-bin/click?id=8o62EdvRBtw&offerid=924365.3184&subid=0&type=4',
    path: 'https://ad.linksynergy.com/fs-bin/show?id=8o62EdvRBtw&bids=924365.3184&subid=0&type=4&gridnum=9',
    name: 'Sam\'s Club',
    is_iframe: 'false',
    iframe: '',
    platform: 'rotate',
    priority: '3',
  },
  {
    url: goToExtension(),
    path: freedomAd,
    name: 'Freedom Super Saver',
    is_iframe: 'false',
    iframe: '',
    platform: 'arcade',
    priority: '8',
  },
];
